### ISSUE TITLE
Does not auto-recover when MQTT broker goes offline

### ISSUE THREAD

**Issue by mjmeli** [briis/hass-weatherflow2mqtt#46] opened 2021-07-13 22:55 UTC
If the MQTT broker goes offline for whatever reason, I'm noticing that weatherflow2mqtt does not attempt to auto-reconnect. I have to restart the weatherflow2mqtt Docker container for the publishing to pick back up. Even a quick restart on the MQTT broker will trigger this.

Pretty straight-forward to reproduce. Take down the MQTT broker for a second (I just restart its Docker container), and publishing will stop. 

Note that I also don't see any logs from the weatherflow2mqtt container logs indicating a lost connection, which might also be helpful.

**Comment by briis** [comment] 2021-07-14 04:53
I will look in to this.
In order to get Debug data from the MQTT Broker, you need to enable it, by adding `-e MQTT_DEBUG=True` to the run command. But this then outputs all MQTT traffic. I will see how I can improve this.

**Comment by briis** [comment] 2021-07-17 06:54
If your MQTT broker goes down, for whatever reason, you will have to restart this container, after MQTT is back up. I know the cause, but I need to find a smart way around this, which might require a bigger rewrite. But for now, just restart the Weatherflow2mqtt container.

**Comment by cmsimike** [comment] 2021-07-24 22:14
@briis https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php#publishing

`publish` returns a `MQTTMessageInfo` where rc can be  `MQTT_ERR_NO_CONN` if the client is not currently connected
https://github.com/eclipse/paho.mqtt.python/blob/0cc8581aa11dbea31364619c1bec6f920dbfec3e/src/paho/mqtt/client.py#L290

As a quick solution, would it be possible to monitor the return value of `publish` and if `rc` = `MQTT_ERR_NO_CONN` manually call `client.reconnect()`?

**Comment by briis** [comment] 2021-07-25 11:46
The issue I have not implemented the MQTT broker using the built-in callbacks, so these values are not available to me. I will have to re-write the way MQTT is setup, which was on my list already. So unfortunately, this is not just a quick fix, due to my wrong implementation from the beginning.

**Comment by GlennGoddard** [comment] 2021-12-13 14:45
Just to report that now when I restart HA, I must also restart WF every time in order to get data again.  Not that big of a deal but I don't think that is the intended consequence.

**Comment by briis** [comment] 2021-12-13 14:46
Are you running as a HA Add-On or as a separate Docker Container?

**Comment by GlennGoddard** [comment] 2021-12-13 16:33
I am using the Docker Container.

**Comment by briis** [comment] 2021-12-14 12:47
I cannot replicate that - I just made a similar setup as yours. Separate Docker Container, feeding in the MQTT. And when I restart Home Assistant, it takes up to a minute, and then all data is shown again without restarting the Container.

**Comment by briis** [comment] 2021-12-30 05:54
This should be fixed with the 3.0.6 release. Please re-open if that is not the case.

**Closed by briis** 2021-12-30 05:54 UTC
Labels: enhancement

**Comment by GlennGoddard** [comment] 2022-02-09 04:47
Had an issue with this just now.  MQTT container restarted and I stopped getting any updates.  I restarted the WF container and all was well in the world.  It is late, so I did not look at any logs; I will try to reproduce this weekend if possible.
