### ISSUE TITLE
Values stop updating after a few minutes after update to 3.0.3

### ISSUE THREAD

**Issue by WhistleMaster** [briis/hass-weatherflow2mqtt#121] opened 2021-12-17 14:35 UTC
Hi !

I've upgraded from 2.2.4 to 3.0.3 and followed all the breaking changes. 

The values are updating correctly at the beginning but after a few minutes, between 10 to 30 minutes, no updated values are coming. I had no issue with version 2.2.4, not sure what could cause the problem as I don't see any error message in the log. 

After a restart of the docker, it's working fine for a few minutes and then stops again.

Happy to help debug the issue,
Kind regards,

WM

**Comment by muxel66** [comment] 2021-12-17 14:57
Same for me, started with 3.0 I think. I guess it is the same as issue#46. I use the add-on on HA OS.

**Comment by WhistleMaster** [comment] 2021-12-17 15:02
I'm not sure it's related to #46, as I have the issue even after a restart of the weatherflow2mqtt: values are updating and then, after a few minutes, no updated values. I don't use the add-on by the way, not sure if it changes anything. I'll try to revert back to 2.2.4 in the meantime.

**Comment by GlennGoddard** [comment] 2021-12-18 06:42
I am currently on the latest Dev build (so if this does not currently work for the latest stable, it will when pushed to stable)

I had same issues.  I have resolved the issues.
I stopped the container.
Deleted the database file.
Deleted all related MQTT from broker.
Removed all WF MQTT related sensor in HA.
Remapped weather (configuration.yaml) and all Lovelace displays to new sensors (I had changed all originally back to WF_, but that does not last over container restarts, so I have the new defaults)
Restarted WF container and updated HA container to the latest point release (why: because I like to insert uncertainty factors in my troubleshooting; why change just one thing when you can change multiple and not know what really did it)

**Comment by GlennGoddard** [comment] 2021-12-18 07:50
Well...it lasted for 3hrs then everything stopped updating; restarted wf container and restored to HA.  It is midnight here, I am going to sleep and will turn on debug when I get up.

**Comment by WhistleMaster** [comment] 2021-12-18 08:01
I reverted back to 2.2.5 yesterday and no issue at all, the values are still updating 17 hours later. I guess there is something with the 3.x version.

**Comment by briis** [comment] 2021-12-18 08:38
If you turn on Debug, does nothing show in the log?

@natekspencer Could you look at this?

**Comment by WhistleMaster** [comment] 2021-12-18 12:28
I will try this weekend to see what happens in the log and post here.

**Comment by natekspencer** [comment] 2021-12-18 17:15
Having debug enabled and then providing the last few logs after it stops responding will be very helpful to try to determine where the issue is. It also may be necessary to look in the logs for Home Assistant core and your MQTT broker to see if anything has manifested there. Please also provide the version of Home Assistant that you are on to potentially see if there is a version incompatibility that we need to address.

**Comment by muxel66** [comment] 2021-12-18 18:36
Here are my logs, however I'm not sure if they help. My Tempest went into low voltage shutdown last night.
Im on HA OS on Odroid, using HA 2021.12.3
[2021-12-18_logs.txt](https://github.com/briis/hass-weatherflow2mqtt/files/7739759/2021-12-18_logs.txt)

**Comment by natekspencer** [comment] 2021-12-18 19:02
> Here are my logs, however I'm not sure if they help. My Tempest went into low voltage shutdown last night. Im on HA OS on Odroid, using HA 2021.12.3 [2021-12-18_logs.txt](https://github.com/briis/hass-weatherflow2mqtt/files/7739759/2021-12-18_logs.txt)

This is perfect actually. There's some values that come back as null that I didn't think was possible (probably from being in low voltage shutdown), which is causing the library to crash. I'll get that fixed!

**Comment by rccoleman** [comment] 2021-12-19 02:04
I'm also seeing this stop receiving data quite quickly after starting, even with a container that I built from the tip that includes `pyweatherflowudp==1.1.2` (verified in the container).  It receives a few UDP packets, but then just seems to stop receiving anything and only periodically updates the forecast via MQTT.  If I concurrently run `nc -u -k -l 50222` **on a different machine**, I see the packets that the weatherflow2mqtt reports in the debug log, and then it continues to periodically receive more packets that aren't reflected in the weatherflow2mqtt logs.

[logs.txt.zip](https://github.com/briis/hass-weatherflow2mqtt/files/7740217/logs.txt.zip)

**Comment by natekspencer** [comment] 2021-12-19 04:20
Thanks, I think I found the bug with that now!

**Comment by natekspencer** [comment] 2021-12-19 04:33
@rccoleman can you try a new build and see if that resolves your issue?

**Comment by rccoleman** [comment] 2021-12-19 04:36
Sure, in a few mins.

**Comment by natekspencer** [comment] 2021-12-19 04:37
> Sure, in a few mins.

No problem. Also thank you for validating that pyweatherflowudp was running fine in the demo, that helped limit the scope as well

**Comment by rccoleman** [comment] 2021-12-19 04:56
That seems to have fixed it!

**Comment by GlennGoddard** [comment] 2021-12-19 06:25
So are we skipping the dev build and going right to latest?

**Comment by natekspencer** [comment] 2021-12-19 06:31
> So are we skipping the dev build and going right to latest?

The last couple of merges haven't been built in docker yet, so they only exist on the master branch. I don't know how to do the docker builds yet, but @briis will be able to get that taken care of

**Comment by GlennGoddard** [comment] 2021-12-19 06:34
Yep, I just looked at DockerHub to verify and you are right it has been 3 days since any build.  Guess I will manually update the files in the container for now then

**Comment by natekspencer** [comment] 2021-12-19 06:41
Let me know if this one stops updating after a while, too. I added a few more debug points to help try and pinpoint the last step that happened before it ceases to communicate.

**Comment by rccoleman** [comment] 2021-12-19 06:54
Sure, will do.  You may also want to fix the `image:` tag in the example `docker-compose.yaml`, since it currently points to the Github container repo that hasn't been updated in a long time.  I puzzled over that for a while until I examined the Docker run command more closely.

**Comment by briis** [comment] 2021-12-19 07:10
Sorry Guys, Timezones suck😁 I have now made a `dev` build of the latest files. It will still be called 3.0.3, but I will change that to 3.0.4 once we agree that things are fixed.

I also changed the image pointer in `docker_compose.yml` as pointed out by @rccoleman. Thanks

**Comment by GlennGoddard** [comment] 2021-12-20 00:54
Lastest dev build still stops.  I have debug on and it is still running 28 mins later.
Looking at when it last stopped working and things that changed: it appears that I changed battery mode back to '0' about when it stopped working.  Based on a rough guess looking at the App and at the current battery level, if I don't get any more sun then in 4 days I will be back down in a different mode.  Since my forecast says 90% chance of rain then I might get more data.

We may have had this issue for awhile but since most of us are just getting to our first winter with Tempest and this program, it just may never have been caught.  So there may have been another issue that was fixed and we just found another one.

**Comment by natekspencer** [comment] 2021-12-20 00:57
Can you share your last logs to see where it stopped? That way I can help see what changes may be needed to keep it running.

**Comment by GlennGoddard** [comment] 2021-12-20 01:04
Well....I didn't have debug running at that time and I trashed the container and started over, so no.

**Comment by natekspencer** [comment] 2021-12-20 01:07
Oh... 😬

**Comment by GlennGoddard** [comment] 2021-12-20 01:54
I will have the logs this time thou.  It was working yesterday, so I turned off the debug.  I got sun today, Tempest charged (a little) and container died.  I can not for certain say that the change in battery mode caused the issue but it seems to be the common issue.  I am at over an hour latter and it is still working.

**Comment by GlennGoddard** [comment] 2021-12-21 01:26
I believe this issue is resolved and we 'might' have a separate issue when battery mode changes.  Awaiting further voltage drop at my end only 0.07 volts to go

**Comment by GlennGoddard** [comment] 2021-12-21 03:25
Going from Battery Mode 0 to 1 is stable.

**Comment by briis** [comment] 2021-12-21 06:26
Seems it is working for @GlennGoddard. Could some of the other people experiencing this, please test the latest `dev` build, and let us now if things have become stable now? Then we can release the V3.0.4

**Comment by leonardpitzu** [comment] 2021-12-21 17:16
latest dev and it stopped for me as well...

**Comment by GlennGoddard** [comment] 2021-12-21 17:21
What battery mode is your Tempest in?  Did it stop at a time when there was sun and probably charging?

**Comment by leonardpitzu** [comment] 2021-12-21 17:27
It stopped some hours ago, about 2 before sunset (northern hemisphere). That's about the time the sunlight is not on the side of house where the weather station is. Right now battery mode is reported as 2. I have no history of the value as i have no use for it (history is tuned to what i need in order to keep the DB small). battery level is 58% (been like this for 2-3 days, goes a bit up but not much).

**Comment by natekspencer** [comment] 2021-12-21 17:31
Do you have any debug logs from around when it stopped updating? It would be beneficial to see the last message that came in.

**Comment by GlennGoddard** [comment] 2021-12-21 17:32
Last time my instance stopped updating data was when it went went back up to mode 0.
How long had it been running before it stopped updating?
The WeatherFlow app is a convenient way to get the history since it is stored on their servers.

For logs:
[https://docs.docker.com/engine/reference/commandline/container_logs/](https://docs.docker.com/engine/reference/commandline/container_logs/)

**Comment by leonardpitzu** [comment] 2021-12-21 17:38
It died at 14:04 and now its 19:36 so about 5h ago.
[logs.txt](https://github.com/briis/hass-weatherflow2mqtt/files/7757087/logs.txt)

**Comment by natekspencer** [comment] 2021-12-21 18:04
Do you have logs from your MQTT broker? Looking at these logs, the last update from the device came in just before the logs. So this may be related to #46 instead.

**Comment by leonardpitzu** [comment] 2021-12-21 18:07
the container was restarted - i have a script which does this unless new data is in... the broker seemed ok but nevetheless here are the logs.
[logs.txt](https://github.com/briis/hass-weatherflow2mqtt/files/7757209/logs.txt)

**Comment by natekspencer** [comment] 2021-12-21 18:11
Oh thanks, I was only looking at the bottom section and not in the middle. Let me take another look through them

**Comment by GlennGoddard** [comment] 2021-12-21 18:27
My 2 cents after looking at the logs; it looks like the unit was charging and right before the pause in logs there was a recorded UV/Light sensor failure.

**Comment by leonardpitzu** [comment] 2021-12-21 18:44
Maybe due to ice or so… at least you have a lead now and can fix it (hopefully)

**Comment by natekspencer** [comment] 2021-12-21 19:12
> UV/Light sensor failure

Yup, saw that too. Working on a fix, but have to do a Christmas lunch with coworkers before I can complete it

**Comment by GlennGoddard** [comment] 2021-12-22 04:40
Mine went down 4 hours ago at around 1600.  Looking at the output of the logs it is saying that the current time of 20:17 is 04:17.   Log is rather large since it is a few days.
[wf.log](https://github.com/briis/hass-weatherflow2mqtt/files/7760012/wf.log)
I have not had a chance to dive into it yet but mine failed also right after a light/uv failure (which it was already dark at that time)

**Comment by natekspencer** [comment] 2021-12-22 04:41
The code in the main branch should take care of @leonardpitzu's issue. There's no docker build yet, but @briis will take care of that when he wakes up since it is still very early in the AM.

**Comment by natekspencer** [comment] 2021-12-22 04:43
> Mine went down 4 hours ago at around 1600. Looking at the output of the logs it is saying that the current time of 20:17 is 04:17. Log is rather large since it is a few days. [wf.log](https://github.com/briis/hass-weatherflow2mqtt/files/7760012/wf.log) I have not had a chance to dive into it yet but mine failed also right after a light/uv failure (which it was already dark at that time)

Yours is very similar and is covered in the changes I made

**Comment by GlennGoddard** [comment] 2021-12-22 04:46
It must be related to going in and out of mode 2 which mine is currently in.
I can manually update my image with the your last PR and test, can't do anymore damage since as soon as my Tempest goes to charge it will fail again tomorrow.

**Comment by briis** [comment] 2021-12-22 04:47
I am building 3.0.4 right now Glenn, should be done in 5-10 minutes

**Comment by natekspencer** [comment] 2021-12-22 04:47
> It must be related to going in and out of mode 2 which mine is currently in. I can manually update my image with the your last PR and test, can't do anymore damage since as soon as my Tempest goes to charge it will fail again tomorrow.

@briis is building an image already, so you should just be able to use that momentarily

**Comment by GlennGoddard** [comment] 2021-12-22 04:47
That is much easier, I guess I will wait then.

**Comment by GlennGoddard** [comment] 2021-12-22 04:51
That is quite a few changes.  This should be perfect for testing since I am currently in a state that will fail when I go from mode 2 to 1, we should know tomorrow since I am just at the cusp of the transition.

**Comment by briis** [comment] 2021-12-22 04:54
3.0.4 is now available

**Comment by GlennGoddard** [comment] 2021-12-22 20:00
Still working, but I also don't have any sun therefore no charging therefore no getting out of Mode 2.
Current forecast is 'maybe' some sun (i.e. from current 200% cloud coverage to peaks of this mythical glowing orb in the sky between snowing clouds).

**Comment by natekspencer** [comment] 2021-12-22 20:09
If you still have debug on, one of the key pieces of information you can look for in the logs is "null" to see if it is being handled. The change back and forth between battery modes is not indicative itself, but it does cut off some sensors to preserve power when this happens, resulting in a certain set of "null" values that were previously causing issues.

**Comment by GlennGoddard** [comment] 2021-12-22 20:16
I do have debug on, but it will be a few hours until I get back home to be able to look thru the logs.
If I restarted and I was in Mode 2 already, it kept running (previous build); it appears that it only stopped on the transition of sensors being dropped off.

**Comment by leonardpitzu** [comment] 2021-12-24 06:43
3.0.4 seems to fix the issue, thanks for your efforts.

**Comment by GlennGoddard** [comment] 2021-12-24 07:50
This appears to be stable.  I would say after the latest icon PR gets a docker dev build and there are no issues with that then all should be good for a stable build.

**Comment by briis** [comment] 2021-12-24 08:07
Agree. I will build 3.0.5 now.

**Comment by briis** [comment] 2021-12-24 08:11
3.0.5 is now released. Closing this issue.

**Closed by briis** 2021-12-24 08:11 UTC

**Comment by GlennGoddard** [comment] 2021-12-26 08:28
Been reliable for a few days now, so probably good for stable.

**Comment by GlennGoddard** [comment] 2021-12-26 17:59
Scratch that 'all good'.  My weather forecast stopped updating yesterday.
Logs to follow.

**Comment by natekspencer** [comment] 2021-12-27 17:07
@GlennGoddard let's log this as a separate issue.
