### ISSUE TITLE
Integration not working all of a sudden

### ISSUE THREAD

**Issue by chris-in-texas** [briis/hass-weatherflow2mqtt#238] opened 2023-08-30 16:17 UTC
All of a sudden nothing is working in the integration.  Looking at the logs:
Logger: homeassistant.config_entries
Source: config_entries.py:1250
First occurred: 9:27:22 AM (3 occurrences)
Last logged: 11:13:51 AM

Config entry 'Claremont Springs' for weatherflow integration not ready yet: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'sea_level_pressure'; Retrying in background
Config entry 'Claremont Springs' for weatherflow integration not ready yet: Error while retreiving data: Empty dataset returned from WeatherFlow. Make sure the station is online.; Retrying in background

This started last night (8/29) and nothing is working even forecasts dashboards etc.  The Weatherflow Local integration is working and data is being received from the unit directly.  Also my Tempest app and website data are working and updating correctly.  Not sure what exactly happened here.

I tried removing and re-adding the integration and still fails, so I am not sure.

Thanks,
Chris

**Comment by briis** [comment] 2023-08-30 18:44
Hi Chris,
I have moved your issue to the correct Integration.

There is something with forecast that makes it crash. I need a bit of time to figure out what it is. If you clear the STATION ID and STATION TOKEN (Set them to blank) and restart the integration, it should work - just without the Weather Forecast.

**Comment by briis** [comment] 2023-08-31 16:56
I have released V2.3.1, which should solve this issue.
The reason for this is that on some stations the Hourly Forecast is not returning a value for Sea Level Pressure and sometimes also UV. I am not sure why this happens, and why only on some stations, but the issue is with WeatherFlow.
This release now returns a 0 value, if no data is returned for the above two items, but ensures that the rest of the flow will still run.

Please let me know if this fixes the issue.

**Comment by briis** [comment] 2023-09-01 05:39
This was a duplicate of #234 and they report it fixed, so I will close this.

**Closed by briis** 2023-09-01 05:39 UTC
